# Generated by Django 4.2.4 on 2023-08-22 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='octoData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.IntegerField(verbose_name='Cost')),
                ('pub_date', models.DateTimeField(verbose_name='Valid to')),
            ],
        ),
        migrations.DeleteModel(
            name='data',
        ),
    ]
