# Generated by Django 4.2.4 on 2023-08-23 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_octodata_delete_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='octoData',
        ),
    ]
